### ISSUE TITLE
Amendments on Assignment 1

### ISSUE THREAD

**Issue by cristinadavila** [SES-5215-F2020/cdavilagonzalez-quant#1]
After receiving your insight on a more practical selection of variables, I've made some changes that would hopefully make my data work for the upcoming assignments.

https://ses-5215-f2020.github.io/cdavilagonzalez-quant/Assignment-1.html

 If you have any chance to give it a quick look, feel free to do so and provide me with some feedback :)

thank you!!

**Comment by saratepfer** [comment]
Great work on this! A small tweak to your code for clarity: I suggest revising line 56 to be consistent with the filter you actually used (49).
