### ISSUE TITLE
Assignment 2 ready for revision/grading.

### ISSUE THREAD

**Issue by cristinadavila** [SES-5215-F2020/cdavilagonzalez-quant#2]
Hello! Calculations only (Rmd+html) and CDG_Quant Assignment 2 Report are the files I'm uploading for grading. Report base (Rmd+html) files were uploaded in case it might be necessary (a reference to charts displayed in the report).  I'm manually uploading all documents related to Assignment 2, after some time trying to commit and push without success. As advised by Prof. Voulgaris, I'll elaborate more on my commit/push inquiry in the platforms she suggested for public consultation.

I hope you like it! I look forward to your feedback.

best,

cdg.

**Comment by saratepfer** [comment]
Thank you, Cristina! Nice job on this! A few comments below

**Comments on Code**
- If you would like to convert your x axis labels from scientific notation on your income graph, you can insert the following code between lines 128 and 129: options(scipen = 999).

**Comments on Content**
- The first table on p7 seems to be mis-named. I believe it should be named "Grade Level Attending"?
